---
version: "3.7"
services:

  # Frontend API
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: 
      - ./frontend:/app
      # Anonymous volume to prevent overwrite
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_URL: http://localhost:5001 # Requests are sent from local browser (outside the Docker network)

# Backend API
  backend:
    env_file: ./backend/.env.dev
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    depends_on:
      - mariadb
    volumes:
      - ./backend/src:/app/src
    ports:
      - 5001:5001

# Database
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      # Todo: user for the application / dotenv files instead here
      MYSQL_ROOT_PASSWORD: rooten
      MYSQL_DATABASE: testdb
      MYSQL_USER: expressuser
      MYSQL_PASSWORD: expresspassword
    volumes:
      - ./database/sql/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
      - ./database/config:/etc/mysql/conf.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
